### ISSUE TITLE
Support `UniformScaling` in multivariate normal constructors

### ISSUE THREAD

**Issue by bartvanerp** [ReactiveBayes/ExponentialFamily.jl#176]
I was just running some code from a couple months ago and it seems that we lost the following functionality:
```julia
MvNormalMeanCovariance(randn(4), 100I)
```
It throws
```julia
MethodError: no method matching ExponentialFamily.MvNormalMeanCovariance(::Vector{Float64}, ::LinearAlgebra.UniformScaling{Int64})
```

In terms of user-friendliness the above syntax should be supported again, whilst maintaining the computational benefits of the `UniformScaling` struct.

**Comment by bvdmitri** [comment]
I've checked `ReactiveMP@3.11.1` before integration with ExponentialFamily.jl and it did work there as well, but it materialised the matrix (using the `Diagonal` type). So its definitely a regression. Can you work on it @bartvanerp ? If yes, I add it to the [milestone](https://github.com/biaslab/RxInfer.jl/milestone/4).
