### ISSUE TITLE
prod between Wishart and WishartFast is not defined

### ISSUE THREAD

**Issue by bvdmitri** [ReactiveBayes/ExponentialFamily.jl#192]
Apparently we did not define an analytical product between `Wishart` and `WishartFast`. `WishartFast` is just slightly more optimized version of `Wishart` , which we use for messages. I propose for such a `prod` we simply `convert` `Wishart` to `WishartFast` and just call the product between two `WishartFast` objects. 

```julia
BayesBase.default_prod_rule(::Type{<:Wishart}, ::Type{<:WishartFast}) = PreserveTypeProd(Distribution)

function BayesBase.prod(::PreserveTypeProd{Distribution}, left::Wishart, right::WishartFast)
    return prod(PreserveTypeProd(Distribution), convert(WishartFast, left), right)
end
```

We can put a new product right after [this one](https://github.com/ReactiveBayes/ExponentialFamily.jl/blob/5b22e10269be19e5b451e36a507dcb18e712acf3/src/distributions/wishart.jl#L189). And the `convert` methods are already implemented [here](https://github.com/ReactiveBayes/ExponentialFamily.jl/blob/5b22e10269be19e5b451e36a507dcb18e712acf3/src/distributions/wishart.jl#L98), so no extra work required for them.

@Nimrais can you add those and also implement similar for `InverseWishartFast`?

**Comment by bvdmitri** [comment]
also the conversion does not work, e.g. `convert(ExponentialFamilyDistribution, Wishart(2.0, Matrix(30.0I(2))))`

**Comment by Nimrais** [comment]
https://github.com/ReactiveBayes/ExponentialFamily.jl/pull/217
